### ISSUE TITLE
[TP4] 2-Creación del @controller y model

### ISSUE THREAD

**Issue by JoyBoy369** [JoyBoy369/Tp2_Grupo20#21]
- [x] crear el paquete denominado controller con las clases tipo java @controller
- [x] crear el paquete model y adentro crear las clases: Producto, Servicio, Sucursal, Noticia y otras.

**Comment by Fran-2811fer** [comment]
Esta tarea fue realizada correctamete por Fernandez Francisco Jesus Maria
